Play travis
Otus-DevOps-2021-02/geckonoff_infra pull request #1
Opened 2021-03-15 10:43 UTC by geckonoff

2021-03-15 10:44 UTC, geckonoff commented
Pull request

2021-03-16 11:55 UTC, mrgreyves requested changes
![image](https://user-images.githubusercontent.com/34331259/111304981-75bce800-8667-11eb-909a-68303dc3ad42.png)
Здравствуйте!) Не забывайте добавлять описание к вашим пр, так же вам стоит починить тесты. ДЗ возвращаю на доработку.

2021-03-16 11:55 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
👀  👀  👀

2021-03-16 14:23 UTC, geckonoff commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Что значит починить тесты?
Я не особо пока разбираюсь в Git

2021-03-16 15:42 UTC, geckonoff commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
> 👀 👀 👀

А ну тест вроде починился.

2021-03-17 11:58 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Все верно, тесты вы починили =)

2021-03-17 11:58 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
![image](https://user-images.githubusercontent.com/34331259/111463978-42469000-8731-11eb-938e-a13ed0503336.png)
Результаты прохождения тестов показываются вот тут =)

2021-03-17 11:59 UTC, mrgreyves requested changes
Здравствуйте!) Стоит обновить описание к вашему дз, в нем можно написать что вы делали и каких результатов достигли =)
![image](https://user-images.githubusercontent.com/34331259/111464079-64d8a900-8731-11eb-8c86-809fb6b3bd70.png)

2021-03-17 14:17 UTC, geckonoff commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
И комменты я вроде тоже добавил.

2021-03-18 07:34 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-03-19 06:18 UTC, mrgreyves commented
Здравствуйте!) После успешной сдачи дз, не забывайте мержить свои ветки в main =)
![image](https://user-images.githubusercontent.com/34331259/111739455-20b1e980-8894-11eb-88da-d202a0c19dad.png)

2021-03-19 07:39 UTC, geckonoff commented
ДЗ выполнено. Можно мерить

2021-03-19 07:40 UTC, merged